---
language: python

python:
 - 2.7

install:
  - pip install PyYAML

before_script:
  - git clone https://github.com/mpdehaan/revelator.git

script:
  - python syntax_check.py *.yml
  - python build_single.py > fundamentals.yml; cd revelator; ./write_it ../fundamentals.yml fundamentals/
  - python syntax_check.py operational/*.yml
  - python build_single.py operational/ > operational.yml; cd revelator; ./write_it ../operational.yml operational/
